### ISSUE TITLE
请给于创建分支权限

### ISSUE THREAD

**Issue by keda** [zhouzhongyuan/cordova-plugin-baidu-push#1]
## 百度SDK升级至V5.2版
android环境下测试通过，已测试机型：小米3、红米NOTE、华为

Iphone 待测试

请给予权限我提交 一个分支

**Comment by zhouzhongyuan** [comment]
已经拉你进入，尽情提交。
[https://github.com/zhouzhongyuan/cordova-plugin-baidu-push/invitations](https://github.com/zhouzhongyuan/cordova-plugin-baidu-push/invitations)
